# https://github.com/greshake/i3status-rust/blob/2dc958995834b529a245c22c510b57d5c928c747/src/themes.rs
[theme]
name = "plain"

# See i3 config for values of $variable
[theme.overrides]
idle_bg = "#2e3440"        # $background
idle_fg = "#7b88a1"        # $foreground
info_bg = "#88c0d0"        # $info
info_fg = "#2e3440"        # $background
good_bg = "#a3be8c"        # $good
good_fg = "#7b88a1"        # $foreground
warning_bg = "#ebcb8b"     # $warning
warning_fg = "#7b88a1"     # $foreground
critical_bg = "#bf616a"    # $alert
critical_fg = "#2e3440"    # $background
alternating_tint_bg = "#000000"
alternating_tint_fg = "#000000"
separator = "  "
separator_bg = "#2e3440"  # $background
separator_fg = "#7b88a1"  # $foreground

# https://github.com/greshake/i3status-rust/blob/2dc958995834b529a245c22c510b57d5c928c747/src/icons.rs#L4
[icons]
name = "awesome"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = "{icon} {available}"
  
[[block]]
block = "sound"

[[block]]
block = "net"
device = "enp3s0"
# format = "{ip} {speed_down;M}"
format = "{ip}"
interval = 5
  
[[block]]
block = "load"
interval = 1
format = "{1m}"
  
[[block]]
block = "memory"
format_mem = "{mem_used_percents}"
display_type = "memory"
icons = true
interval = 5
warning_mem = 70
warning_swap = 70
critical_mem = 85
critical_swap = 85
  
[[block]]
block = "time"
interval = 60
format = "%Y-%m-%d (%a) %H:%M"
