# https://github.com/greshake/i3status-rust/blob/2dc958995834b529a245c22c510b57d5c928c747/src/themes.rs
[theme]
name = "plain"
# Zenburn, except the idle_bg/fg which are dark-black and yellow,
# according to my i3 conf
[theme.overrides]
idle_bg = "#0f0f0f"        # Dark black
idle_fg = "#f0dfaf"        # Yellow
info_bg = "#6b3654"        # Purple
info_fg = "#f0dfaf"
good_bg = "#7f9f7f"        # Green
good_fg = "#f0dfaf"
warning_bg = "#f0dfaf"     # Yellow
warning_fg = "#0f0f0f"
critical_bg = "#cc9393"    # Red
critical_fg = "#f0dfaf"
alternating_tint_bg = "#000000"
alternating_tint_fg = "#000000"
separator = "  "
separator_bg = "#0f0f0f"
separator_fg = "#f0dfaf"

# https://github.com/greshake/i3status-rust/blob/2dc958995834b529a245c22c510b57d5c928c747/src/icons.rs#L4
[icons]
name = "awesome"
[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "disk_space"
path = "/home"
alias = "/home"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "sound"

[[block]]
block = "net"
device = "enp3s0"
ip = true
speed_up = false
speed_down = false
interval = 5

# [[block]]
# block = "memory"
# display_type = "memory"
# format_mem = "{Mup}%"
# format_swap = "{SUp}%"

# [[block]]
# block = "cpu"
# interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "time"
interval = 60
format = "%Y-%m-%d (%a) %H:%M"
